# Generated by Django 5.0.6 on 2024-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug_alter_post_status_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='post_imagens/', verbose_name='Imagem'),
        ),
    ]
