# Generated by Django 5.0.6 on 2024-06-11 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem_destaque',
            field=models.ImageField(upload_to='post/', verbose_name='Imagem em Destaque'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
